FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

RUN uv pip install --system dbt-bigquery==1.10.0
