version: 2

sources:
  - name: raw_data
    database: fruit-packing-plant-simulator  # Your Project Name
    schema: raw_dataset   # Your Dataset Name
    tables:
      - name: batches_ext
      - name: events_ext
      - name: satellite_ext
      - name: telemetry_ext
