seeds:
  - name: fruit_specific_params
    config:
      column_types:
        fruit_type: string
        heat_damage_temp_c: float64
        chill_damage_temp_c: float64
        heat_damage_minutes_threshold: int64
        chill_damage_minutes_threshold: int64
        rh_low_threshold: float64
        rh_high_threshold: float64
        rh_low_damage_minutes_threshold: int64
        q_rated_kw: float64
        td_design: float64
        bf: float64
