id: master_flow
namespace: blueberry_cold_storage

inputs:
  - id: start_of_operations
    type: STRING
    description: "First day of the months when the facility started recording data, e.g. 2022-01-01"
    defaults: "2022-01-01"

  - id: start_date
    type: STRING
    description: "Start date of the month to be simulated, e.g. 2025-01-01. Only relevant for testing"
    defaults: "{{ trigger.date ?? execution.startDate | dateAdd(-1, 'MONTHS') | date('yyyy-MM-dd') }}"

  - id: is_test
    type: STRING
    defaults: "false"
    description: "Leave in false for regular runs"

  - id: frequency
    type: STRING
    defaults: "hourly"

  - id: seed
    type: INT
    defaults: 42

  - id: fruit_types
    type: ARRAY
    itemType: STRING
    defaults: ["blueberry", "avocado"]
    description: "List of fruits for which to generate data"

pluginDefaults:
  - type: io.kestra.plugin.gcp
    values:
      serviceAccount: "{{secret('GCP_SERVICE_ACCOUNT')}}"
      projectId: "{{kv('GCP_PROJECT_ID')}}"
      location: "{{kv('GCP_LOCATION')}}"
      bucket: "{{kv('GCP_BUCKET_NAME')}}"

tasks:
  - id: create_bq_tables
    type: io.kestra.plugin.core.flow.Subflow
    flowId: bq_setup
    namespace: blueberry_cold_storage
    wait: true
    transmitFailed: true
    runIf: "{{ kv('bq_tables_created') == 'false' }}"

  - id: run_historical_backfill
    type: io.kestra.plugin.core.flow.Subflow
    flowId: backfill_historical
    namespace: blueberry_cold_storage
    wait: true
    transmitFailed: true
    runIf: "{{ kv('backfill_complete') == 'false' }}"
    inputs:
      start_of_operations: "{{ inputs.start_of_operations }}"
      frequency: "{{ inputs.frequency }}"
      seed: "{{ inputs.seed }}"
      fruit_types: "{{ inputs.fruit_types }}"
      is_test: "{{ inputs.is_test }}"

  - id: run_monthly_backfill_scheduled
    type: io.kestra.plugin.core.flow.Subflow
    flowId: backfill_monthly_scheduled
    namespace: blueberry_cold_storage
    wait: true
    transmitFailed: true
    runIf: "{{ kv('backfill_complete') == 'true' }}"
    inputs:
      start_date: "{{ inputs.start_date }}"
      frequency: "{{ inputs.frequency }}"
      seed: "{{ inputs.seed }}"
      fruit_types: "{{ inputs.fruit_types }}"
      is_test: "{{ inputs.is_test }}"

  - id: mark_month_iteration_as_complete
    type: io.kestra.plugin.core.kv.Set
    runIf: "{{ kv('backfill_complete') == 'false' }}"
    key: "backfill_complete"
    value: "true"

triggers:
  - id: monthly_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 1 1 * *"  # 1am on the 1st of every month
    timezone: America/New_York
