id: monthly_pipeline
namespace: chao_cold_storage

description: |
  Master orchestration flow for the Chao (Peru) telemetry simulator. 
  Manages stateful historical gap-healing, incremental BigQuery loading, 
  and production dbt data mart execution on a monthly schedule.

inputs:
  - id: is_kestra_backfill
    type: BOOL
    defaults: false
    description: "SET TO true IF RUNNING KESTRA BACKFILL."

  - id: fruit_types
    type: ARRAY
    itemType: STRING
    defaults: ["blueberry", "avocado"]
    description: "List of fruits for which to generate data. Only blueberries and avocados, high-value crops intensively farmed at this location (Chao, Peru), are available for now."

  - id: silence_alerts
    type: BOOL
    defaults: false
    description: "Choose whether to silence email alerts. NOTE: Kestra backfill fill result in alerts for every task run in each iteration."

  - id: is_test
    type: BOOL
    defaults: false
    description: "Leave in false for regular runs."

labels:
  mute_alerts: "{{ inputs.silence_alerts }}"
  environment: production
  layer: orchestration

variables:
  start_date: "{{ trigger.date ?? execution.startDate | dateAdd(-1, 'MONTHS') | date('yyyy-MM-dd') }}"
  frequency: "hourly"
  seed: 42

tasks:
  - id: start_notification
    type: io.kestra.plugin.core.flow.Subflow
    flowId: local_email_alerts
    namespace: chao_cold_storage
    wait: true
    transmitFailed: true
    allowFailure: true
    labels:
      mute_alerts: true
    inputs:
      month: "{{ render(vars.start_date) | date('yyyy-MM') }}"
      is_healing_run: "{{ inputs.is_kestra_backfill == false and kv('pipeline_diagnostics') != 'normal_run' }}"
      parent_flow_id: "{{ flow.id }}"
      parent_execution_id: "{{ execution.id }}"
      parent_namespace: "{{ flow.namespace }}"

  - id: run_diagnostics
    type: io.kestra.plugin.core.flow.Subflow
    flowId: check_simulation_states
    namespace: chao_cold_storage
    wait: true
    transmitFailed: true
    inheritLabels: true
    runIf: "{{ inputs.is_kestra_backfill == false }}"
    inputs:
      start_date: "{{ render(vars.start_date) }}"
      fruit_types: "{{ inputs.fruit_types }}"

  - id: incomplete_historical_message
    type: io.kestra.plugin.core.log.Log
    runIf: "{{ inputs.is_kestra_backfill == false and kv('pipeline_diagnostics') != 'normal_run' }}"
    message: "Historical backfill is not complete. Last date in simulation_state keys will be taken as input to generate data until last available month"

  - id: fill_gaps
    type: io.kestra.plugin.core.flow.Subflow
    flowId: healing_flow
    namespace: chao_cold_storage
    wait: true
    transmitFailed: true
    inheritLabels: true
    runIf: "{{ inputs.is_kestra_backfill == false and kv('pipeline_diagnostics') != 'normal_run' }}"
    inputs:
      start_date: "{{ render(vars.start_date) }}"
      frequency: "{{ vars.frequency }}"
      seed: "{{ vars.seed }}"
      fruit_types: "{{ inputs.fruit_types }}"
      is_test: "{{ inputs.is_test }}"

  - id: exit_early_after_healing
    type: io.kestra.plugin.core.execution.Exit
    runIf: "{{ inputs.is_kestra_backfill == false and kv('pipeline_diagnostics') != 'normal_run' }}"
    state: SUCCESS

  - id: regular_montly_execution_message
    type: io.kestra.plugin.core.log.Log
    runIf: "{{ inputs.is_kestra_backfill == false }}"
    message: "Executing regular monthly run for month {{ render(vars.start_date) | date('yyyy-MM') }}"
      
  - id: initialize_workflow
    type: io.kestra.plugin.core.flow.Subflow
    flowId: initialization_tasks
    namespace: chao_cold_storage
    wait: true
    transmitFailed: true
    inheritLabels: true
    retry:
      type: constant
      interval: PT1M
      maxDuration: PT10M
      maxAttempts: 3
      warningOnRetry: true   
    runIf: "{{ kv('is_initialized') == false }}"
    inputs:
      start_date: "{{ render(vars.start_date) }}"
      fruit_types: "{{ inputs.fruit_types }}"    

  - id: run_monthly_simulation_and_upload
    type: io.kestra.plugin.core.flow.Subflow
    flowId: monthly_run
    namespace: chao_cold_storage
    wait: true
    transmitFailed: true
    inheritLabels: true
    inputs:
      start_date: "{{ render(vars.start_date) }}"
      frequency: "{{ vars.frequency }}"
      seed: "{{ vars.seed }}"
      fruit_types: "{{ inputs.fruit_types }}"

  - id: append_raw_bq_tables
    type: io.kestra.plugin.core.flow.Subflow
    flowId: bq_load_incremental
    namespace: chao_cold_storage
    wait: true
    transmitFailed: true
    inheritLabels: true
    retry:
      type: constant
      interval: PT1M
      maxDuration: PT10M
      maxAttempts: 3
      warningOnRetry: true
    inputs:
      month: "{{ render(vars.start_date) | slice(0, 7) }}"

  - id: execute_dbt
    type: io.kestra.plugin.core.flow.Subflow
    flowId: dbt_build
    namespace: chao_cold_storage
    wait: true
    transmitFailed: true
    inheritLabels: true
    retry:
      type: constant
      interval: PT1M
      maxDuration: PT10M
      maxAttempts: 3
      warningOnRetry: true
    runIf: "{{ inputs.is_test == false }}"
    inputs:
      start_date: "{{ render(vars.start_date) }}"

  - id: mark_historical_data_generation_as_complete
    type: io.kestra.plugin.core.kv.Set
    runIf: "{{ inputs.is_kestra_backfill == true and (kv('backfill_complete') == false) and (render(vars.start_date) == (now().minusMonths(1) | date('yyyy-MM-01'))) }}"
    key: "backfill_complete"
    kvType: BOOLEAN
    value: "true"

triggers:
  - id: monthly_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 1 1 * *"  # 1am on the 1st of every month
    timezone: UTC
    stopAfter:
      - FAILED

