id: one_flow_to_rule_them_all
namespace: blueberry_cold_storage

inputs:
  - id: start_of_operations
    type: STRING
    description: "the month when the cold storage room started operating or recording data"
    defaults: "2022-01-01"

  - id: start_date
    type: STRING
    description: "Start date of the month, e.g. 2022-01-01"
    defaults: "{{ trigger.date ?? execution.startDate | dateAdd(-1, 'MONTHS') | date('yyyy-MM-dd') }}"

  - id: frequency
    type: STRING
    defaults: "hourly"

  - id: seed
    type: INT
    defaults: 42

  - id: fruit_types
    type: ARRAY
    itemType: STRING
    defaults: ["blueberry", "avocado"]
    description: "List of fruits for which to generate data"

variables:
  # current_state: "{{ kv('simulation_state_' ~ inputs.fruit_type) ?? '{\"next_start\":\"2022-01-01T00:00:00\",\"next_batch_id\":1,\"active_batches\":[]}' }}"
  backfill_complete: "{{ kv('backfill_complete') ?? 'false' }}"
  satellite_data_in_lake: "{{ kv('satellite_data_in_lake') ?? 'false' }}"

pluginDefaults:
  - type: io.kestra.plugin.gcp
    values:
      serviceAccount: "{{secret('GCP_SERVICE_ACCOUNT')}}"
      projectId: "{{kv('GCP_PROJECT_ID')}}"
      location: "{{kv('GCP_LOCATION')}}"
      bucket: "{{kv('GCP_BUCKET_NAME')}}"

tasks:
  - id: generate_month_list
    type: io.kestra.plugin.scripts.python.Script
    containerImage: blueberry_simulator:v001
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    namespaceFiles:
      enabled: true
    runIf: "{{ kv('backfill_complete') == 'false' }}"
    script: |
      from datetime import datetime
      from dateutil.relativedelta import relativedelta
      from kestra import Kestra

      # Parse input and get current time
      start = datetime.strptime("{{ inputs.start_of_operations }}", "%Y-%m-%d")
      end = (datetime.now() - relativedelta(months=1)).replace(day=1)
      
      months = []
      current = start.replace(day=1)
      
      while current <= end:
          months.append(current.strftime("%Y-%m"))
          current += relativedelta(months=1)
      
      # Export the list so the next task can see it
      Kestra.outputs({'month_range': months})

  - id: iterate_fruits
    type: io.kestra.plugin.core.flow.ForEach
    concurrencyLimit: 1
    values: "{{ inputs.fruit_types }}"
    tasks:
    - id: iterate_months
      type: io.kestra.plugin.core.flow.ForEach
      concurrencyLimit: 1
      values: "{{ outputs.generate_month_list.vars.month_range }}"
      runIf: "{{ kv('backfill_complete') == 'false' }}"
      tasks:
        - id: run_one_month
          type: io.kestra.plugin.core.flow.Subflow
          flowId: backfill_monthly
          namespace: blueberry_cold_storage
          wait: true
          transmitFailed: true
          inputs:
            start_date: "{{ taskrun.value }}"
            frequency: "hourly"
            seed: "{{ inputs.seed }}"
            fruit_type: "{{ parent.taskrun.value }}"
            is_satellite_data_in_lake: "{{ vars.satellite_data_in_lake }}"

    - id: run_monthly_update
      type: io.kestra.plugin.core.flow.Subflow
      flowId: backfill_monthly
      namespace: blueberry_cold_storage
      runIf: "{{ kv('backfill_complete') == 'true' }}"
      wait: true
      transmitFailed: true
      inputs:
        start_date: "{{ trigger.date ?? execution.startDate | dateAdd(-1, 'MONTHS') | date('yyyy-MM-dd') }}"
        frequency: "hourly"
        seed: "{{ inputs.seed }}"
        fruit_type: "{{ parent.taskrun.value }}"
        is_satellite_data_in_lake: "{{ vars.satellite_data_in_lake }}"

    - id: mark_satellite_data_as_existing
      type: io.kestra.plugin.core.kv.Set
      key: "satellite_data_in_lake"
      value: "true"

  - id: create_raw_bq_tables
    type: io.kestra.plugin.core.flow.Subflow
    flowId: bq_setup
    namespace: blueberry_cold_storage

  - id: execute_dbt
    type: io.kestra.plugin.scripts.shell.Commands
    containerImage: ghcr.io/dbt-labs/dbt-bigquery:1.8.0
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    commands:
      - git clone https://github.com/acasavilca/blueberry-coldchain-analytics.git
      - mkdir -p /root/.dbt
      - |
        cat > /root/.dbt/profiles.yml << EOF
        blueberry_dbt:
          target: prod
          outputs:
            prod:
              type: bigquery
              method: service-account-json
              project: {{kv('GCP_PROJECT_ID')}}
              dataset: {{kv('GCP_DATASET')}}
              location: {{kv('GCP_LOCATION')}}
              keyfile_json: {{secret('GCP_SERVICE_ACCOUNT')}}
              threads: 4
        EOF
      - cd blueberry-coldchain-analytics/dbt && dbt build --profiles-dir /root/.dbt

  - id: mark_month_iteration_as_complete
    type: io.kestra.plugin.core.kv.Set
    runIf: "{{ kv('backfill_complete') == 'false' }}"
    key: "backfill_complete"
    value: "true"

  - id: reset_satelite_data_key_value
    type: io.kestra.plugin.core.kv.Set
    key: "satellite_data_in_lake"
    value: "false"

triggers:
  - id: monthly_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 1 1 * *"  # 1am on the 1st of every month
    timezone: America/New_York
