id: global_email_alerts
namespace: system

triggers:
  - id: on_end
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      # Accept SUCCESS only for root flows, but FAILED for any flow
      - type: io.kestra.plugin.core.condition.Expression
        expression: >
          (trigger.state == 'FAILED') or 
          (trigger.state == 'SUCCESS' and trigger.execution.parentId is null)

      - type: io.kestra.plugin.core.condition.Expression
        expression: "{{ trigger.execution.labels.mute_alerts != true }}"

tasks:
  - id: craft_custom_message
    type: io.kestra.plugin.core.debug.Return
    format: |
      {% if trigger.state == 'FAILED' %}
        <h3>Workflow ERROR 🚨 :</h3>
        <p><strong>Flow:</strong> {{ trigger.flowId }}</p>
        <p><strong>Execution ID:</strong> {{ trigger.executionId }}</p>
        {% if trigger.execution.parentId %}
          <p><strong>Parent Flow:</strong> {{ trigger.execution.parentFlowId }}</p>
          <p><strong>Parent Execution ID:</strong> {{ trigger.execution.parentId }}</p>
        {% endif %}
        <p><a href="{{ kestra.url }}ui/main/executions/{{ trigger.execution.parentNamespace ?? trigger.namespace }}/{{ trigger.execution.parentFlowId ?? trigger.flowId }}/{{ trigger.execution.parentId ?? trigger.executionId }}/logs">Click here to view logs and troubleshoot.</a></p>

      {% else %}
        <h3>Workflow SUCCESS ✅ :</h3>
        <p><strong>Flow:</strong> {{ trigger.flowId }}</p>
        <p><strong>Execution ID:</strong> {{ trigger.executionId }}</p>
        <p><a href="{{ kestra.url }}ui/main/executions/{{ trigger.namespace }}/{{ trigger.flowId }}/{{ trigger.executionId }}">Click here to view your results.</a></p>
      {% endif %}

  - id: send_email_notification
    type: io.kestra.plugin.email.MailSend
    from: "{{ kv('MY_GMAIL') }}"
    to: "{{ kv('MY_GMAIL') }}"
    subject: "Pipeline alert ({{ trigger.state }}): {{ trigger.flowId }}"
    host: smtp.gmail.com
    port: 465
    username: "{{ kv('MY_GMAIL') }}"
    password: "{{ secret('EMAIL_PASSWORD') }}"
    htmlTextContent: "{{ outputs.craft_custom_message.value }}"
      
